services:
  - type: web
    name: rspfi-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "5775087092"
      - key: ADMIN_USERNAME
        value: Smael6667
      - key: SUPPORT_TELEGRAM
        value: https://t.me/ceo_yanFi
      - key: DELIVERY_FEE
        value: "1.50"
      - key: APP_URL
        value: https://rspfi-telegram-bot.onrender.com
